Add Authentication to MQTT & docker-compose file
ps-jay/pyraven-mqtt pull request #1
Opened 2022-06-28 09:35 UTC by Krazy998

- Small update to add MQTT authentication to code 
- Add docker-compose file example.
- Updates to README with additional variables for username and password.

2022-06-28 11:15 UTC, ps-jay requested changes
Thanks for the submission!

I'd like to see this made conditional for backward compatibility

2022-06-28 11:15 UTC, ps-jay commented on README.md
> +    --password=password
Need `\` at the end of the lines for command continuation

2022-06-28 11:15 UTC, ps-jay commented on README.md
> +```
Isn't actually code, so don't put it in a code block

2022-06-28 11:15 UTC, ps-jay commented on docker-compose.yaml
> +    tty: true
Missing EOL character at the end of the line (posix standard)

2022-06-28 11:15 UTC, ps-jay commented on pyrmqtt.py
> +
It would be better to wrap this in a conditional for backward compatibility with folks who use unauthenticated MQTT

2022-06-29 01:31 UTC, Krazy998 commented
I have made the changes as suggested - let me know if that works

2022-07-08 03:58 UTC, ps-jay approved these changes
Thanks for the contribution!

2022-07-08 03:58 UTC, merged